### ISSUE TITLE
InstagramPost type error (must be of the type integer, string given)

### ISSUE THREAD

**Issue by realwahyuputra** [mineur/instagram-parser#1]
Hello, im unable to run the code. It throws me error:
`Fatal error: Uncaught Error: Class 'Mineur\InstagramParser\Instagram' not found in C:\xampp\htdocs\instagram\index.php:7 Stack trace: #0 {main} thrown in C:\xampp\htdocs\instagram\index.php on line 7`
Run on localhost with xampp and composer installed.

**Comment by alexhoma** [comment]
Hi @realwahyuputra, can you show me the code snippet, so I can see how are you running the library? 

Maybe you forgot to add the `use` statement to the Instagram class? or maybe you are not requiring the composer's autoload?

Try to run this snippet on your console:
```php
<?php

// Autoload composer
require_once __DIR__ . '/vendor/autoload.php';

// Imports
use Mineur\InstagramParser\Instagram;

// Run parser
$queryId = '17882293912014529';
Instagram::createTagParser($queryId)
    ->parse('github', function($post) {
        echo $post->getComment();
    });
```

By the way, the `echo` on the README docs is wrong. Is `$post->getComment()` as I show you here, not `$post->getContent()`.

**Comment by realwahyuputra** [comment]
Ah my fault, i forgot to include autoload. But still display error like this:
`
Fatal error: Uncaught TypeError: Argument 1 passed to Mineur\InstagramParser\Model\InstagramPost::__construct() must be of the type integer, string given, called in C:\xampp\htdocs\instagram\vendor\mineur\instagram-parser\src\Model\InstagramPost.php on line 104 and defined in C:\xampp\htdocs\instagram\vendor\mineur\instagram-parser\src\Model\InstagramPost.php:59 Stack trace: #0 C:\xampp\htdocs\instagram\vendor\mineur\instagram-parser\src\Model\InstagramPost.php(104): Mineur\InstagramParser\Model\InstagramPost->__construct('154339691811223...', 'Aunt It on a a ...', 0, 'BVrP1Hbgxxo', 1498207271, Object(Mineur\InstagramParser\Model\MediaDimensions), 0, 'https://instagr...', 'https://instagr...', '14216218', false, false) #1 C:\xampp\htdocs\instagram\vendor\mineur\instagram-parser\src\Parser\TagParser.php(115): Mineur\InstagramParser\Model\InstagramPost::fromArray(Array) #2 C:\xampp\htdocs\instagram\vendor\mineur\instagram-parser\src\Parser\TagParser.php(70): Mineur\InstagramParser\Parser\TagParser->returnPostObject(Array, O in C:\xampp\htdocs\instagram\vendor\mineur\instagram-parser\src\Model\InstagramPost.php on line 59`

This is my snippet (Copy from docs):

```
<?php

// Autoload composer
require_once __DIR__ . '/vendor/autoload.php';

use Mineur\InstagramParser\Instagram;
use Mineur\InstagramParser\Model\InstagramPost;

$queryId = '17882293912014529';
Instagram::createTagParser($queryId)
    ->parse('sun', function(InstagramPost $post) {
        dump($post);
    });
```

**Comment by alexhoma** [comment]
I just updated the code to cast an integer now. It's working on my machine.

So what to do now:
- I recommend you to run `composer update` to apply the new bugfix.
- Run your script again.

Tell me if it's working. Sorry about this, this is a very early version of the library. 
I'm also open to receive pull requests If you see any other bug and you know ho to solve it.

**Comment by alexhoma** [comment]
Hi @realwahyuputra anything new? it worked for you?
